### ISSUE TITLE
Stacer 1.1.0 amd64.deb can not open when it was installed ?

### ISSUE THREAD

**Issue by jay763190097** [oguzhaninan/Stacer#301] opened 2019-07-05 16:31 UTC
I alse can't find any excute file in /usr/share/stacer

**Comment by oguzhaninan** [comment] 2019-07-05 17:16
Hi @jay763190097,
Could you try restart the computer and try again?

**Comment by jay763190097** [comment] 2019-07-07 03:52
sure, There isn't a directory in /usr/share/stacer this path

**Comment by Nilvus** [comment] 2019-07-07 17:12
I confirm that. No /usr/share/stacer directory on my system also after installing that .deb by downloading it from sourceforge repository and dpkg -i to install it. 
But if I add ppa directory and install it with apt install, stacer is here and works great.

**Comment by oguzhaninan** [comment] 2019-10-24 18:26
Hi @jay763190097,
Did you fix this problem?

**Comment by alexmyczko** [comment] 2019-12-06 10:38
Try this:

```
dget http://phd-sid.ethz.ch/debian/stacer/stacer_1.1.0-1.dsc
dpkg-source -x *.dsc
cd stac*/
debuild
cd ..
dpkg -i stacer*.deb
```

**Comment by rustydr34m** [comment] 2019-12-09 15:55
The problem is caused by the deb file. AppImage file working but deb installer not working.

**Comment by alexmyczko** [comment] 2019-12-09 16:04
that is why i provided a recipe to build your own working deb file

**Comment by alexmyczko** [comment] 2020-01-03 19:12
meanwhile there is an official debian package in debian sid, should shortly arrive in ubuntu 20.04 as well

**Comment by alexmyczko** [comment] 2020-02-11 07:28
and a ppa for 19.10: https://launchpad.net/~gagarin/+archive/ubuntu/eoan/+packages

**Comment by alexmyczko** [comment] 2020-05-16 10:16
@oguzhaninan I would close this one as well

**Closed as completed** 2020-05-16 13:56 UTC
